### ISSUE TITLE
Not returning Authorization Token

### ISSUE THREAD

**Issue by torochu** [jameschambers/boring-bits-rails-api#1]
## Problem
I've tried boring-bits-rails-api template, tests were passed. When I registered a user through postman, I got response as follow:
```json
{
    "data": {
        "id": "8",
        "type": "users",
        "attributes": {
            "email": "new@abc.com"
        },
        "links": {
            "self": "http://localhost:3001/api/users/8"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```
It doesn't return an authorization token

## Debugging information
Version of ruby ruby-2.6.2
Version of devise-jwt in use 0.7.0
Version of rails in use 6.0.3

**Comment by jameschambers** [comment]
The token is returned as an `Authorization` response header, rather than in the JSON body itself. See the User Controller Spec: https://github.com/jameschambers/boring-bits-rails-api/blob/master/templates/spec/controllers/users_controller_spec.rb

**Comment by torochu** [comment]
my bad.
thanks for helping me out.
